export const reviewData = [
    { key: 1, location: "Switzerland", name: 'antoninbl', message: "It's been really easy to work with NX Craft . They asked relevant questions to understand the project and delivered it on time with exceptional quality. Already collaborating on a second project with them." },
    { key: 2, location: "France", name: 'kevindfr', message: "Professional, helpful, and highly responsive! Thank you so much, NX Craft , for your outstanding work." },
    { key: 3, location: "India", name: 'doctorshanker', message: "NX Craft  exceeded expectations with their attention to detail, professionalism, bug-free code, technical expertise, and comprehensive documentation." },
    { key: 4, location: "Italy", name: 'aziendefuturo', message: "Collaborating with NX Craft  was a fantastic experience. Their professionalism and dedication to delivering quality work stood out." },
    { key: 5, location: "Bangladesh", name: 'tahshinislam', message: "NX Craft  delivered remarkable results and provided excellent support throughout the project. Highly recommended!" },
    { key: 6, location: "Canada", name: 'lindabc', message: "NX Craft  has been a pleasure to work with. Their team is skilled, innovative, and committed to delivering the best outcomes for their clients." },
    { key: 7, location: "Germany", name: 'marcelg', message: "We were impressed with NX Craft 's expertise and their ability to turn our vision into reality. The project was completed on time and exceeded our expectations." },
    { key: 8, location: "Australia", name: 'emilyoz', message: "NX Craft ’s dedication and professionalism are unparalleled. Their attention to detail and seamless communication made the entire process smooth and efficient." }
];

export const technologies = {
    webDevelopment: [
        { id: 1, name: "React Js" },
        { id: 2, name: "Next Js" },
        { id: 3, name: "Angular" },
        { id: 4, name: "Vue.js" },
        { id: 5, name: "Bootstrap 5" },
        { id: 6, name: "Tailwind CSS" },
        { id: 7, name: "Node.js" },
        { id: 8, name: "Django" },
        { id: 9, name: "Express.js" },
        { id: 10, name: "Spring Boot" },
        { id: 11, name: "Ruby on Rails" },
        { id: 12, name: "PHP Laravel" },
        { id: 13, name: "MySQL" },
        { id: 14, name: "PostgreSQL" },
        { id: 15, name: "MongoDB" },
        { id: 16, name: "SQLite" },
        { id: 17, name: "Redis" },
    ],
    mobileDevelopment: [
        { id: 1, name: "React Native" },
        { id: 2, name: "Flutter" },
        { id: 3, name: "Swift" },
        { id: 4, name: "Kotlin" },
        { id: 5, name: "Java (Android)" },
        { id: 6, name: "Objective-C" },
        { id: 7, name: "Xamarin" },
        { id: 8, name: "Ionic Framework" },
        { id: 9, name: "NativeScript" },
        { id: 10, name: "Apache Cordova" },
        { id: 11, name: "Unity for Mobile" },
        { id: 12, name: "Corona SDK" },
        { id: 13, name: "Sencha Touch" },
        { id: 14, name: "PhoneGap" },
        { id: 15, name: "Firebase" },
        { id: 16, name: "Appcelerator Titanium" },
        { id: 17, name: "SwiftUI" },
    ],
    uiUxTechnologies: [
        { id: 1, name: "Figma" },
        { id: 2, name: "Adobe XD" },
        { id: 3, name: "Sketch" },
        { id: 4, name: "InVision" },
        { id: 5, name: "Axure RP" },
        { id: 6, name: "Marvel App" },
        { id: 7, name: "Balsamiq" },
        { id: 8, name: "Framer" },
        { id: 9, name: "Canva" },
        { id: 10, name: "Zeplin" },
        { id: 11, name: "Principle" },
        { id: 12, name: "Adobe Illustrator" },
        { id: 13, name: "Adobe Photoshop" },
        { id: 14, name: "Proto.io" },
        { id: 15, name: "Webflow" },
        { id: 16, name: "Overflow" },
        { id: 17, name: "Maze" },
    ],
    digitalMarketingTechnologies: [
        { id: 1, name: "Google Ads" },
        { id: 2, name: "Facebook Ads Manager" },
        { id: 3, name: "HubSpot" },
        { id: 4, name: "Hootsuite" },
        { id: 5, name: "Canva" },
        { id: 6, name: "Mailchimp" },
        { id: 7, name: "Buffer" },
        { id: 8, name: "Sprout Social" },
        { id: 9, name: "Google Analytics" },
        { id: 10, name: "Ahrefs" },
        { id: 11, name: "SEMrush" },
        { id: 12, name: "Adobe Marketing Cloud" },
        { id: 13, name: "ActiveCampaign" },
        { id: 14, name: "Marketo" },
        { id: 15, name: "Trello" },
        { id: 16, name: "Slack" },
        { id: 17, name: "Zapier" },
    ],
    graphicDesignTechnologies: [
        { id: 1, name: "Adobe Photoshop" },
        { id: 2, name: "Adobe Illustrator" },
        { id: 3, name: "CorelDRAW" },
        { id: 4, name: "Figma" },
        { id: 5, name: "Adobe XD" },
        { id: 6, name: "Canva" },
        { id: 7, name: "Affinity Designer" },
        { id: 8, name: "Sketch" },
        { id: 9, name: "Procreate" },
        { id: 10, name: "Blender" },
        { id: 11, name: "Inkscape" },
        { id: 12, name: "Gravit Designer" },
        { id: 13, name: "Krita" },
        { id: 14, name: "Vectr" },
        { id: 15, name: "Piktochart" },
        { id: 16, name: "Crello" },
        { id: 17, name: "Adobe After Effects" },
    ],
    seoTechnologies: [
        { id: 1, name: "Google Analytics" },
        { id: 2, name: "Google Search Console" },
        { id: 3, name: "Ahrefs" },
        { id: 4, name: "SEMrush" },
        { id: 5, name: "Moz Pro" },
        { id: 6, name: "Yoast SEO" },
        { id: 7, name: "Rank Math" },
        { id: 8, name: "Screaming Frog" },
        { id: 9, name: "Ubersuggest" },
        { id: 10, name: "SpyFu" },
        { id: 11, name: "Majestic SEO" },
        { id: 12, name: "KWFinder" },
        { id: 13, name: "Serpstat" },
        { id: 14, name: "Google Keyword Planner" },
        { id: 15, name: "Surfer SEO" },
        { id: 16, name: "BrightEdge" },
        { id: 17, name: "DeepCrawl" },
    ],
    
};




export const chatUser = [

    {id:1, first_name:"Brady", last_name:"Burns", chatRoom:"e2237798-51da-466b-ad55-806d4582de52"},
    {id:3, first_name:"Tatum", last_name:"Ford", chatRoom:"e2237798-51da-466b-ad55-806d4582de41"},
    // {id:3, first_name:"Usman", last_name:"Ali", chatRoom:"e2237798-51da-466b-ad55-806d4582de42"},
]
